spring.application.name=api

server.port=${SERVER_PORT:8081}
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=never

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/duckhat?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Sao_Paulo}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:duckhat_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:duckhat_pass}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=${SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL:true}
spring.jpa.open-in-view=false

jwt.secret=${JWT_SECRET:ZHVja2hhdC1zdXBlci1zZWNyZXQta2V5LWR1Y2toYXQtMjAyNi1zZWd1cmE=}
jwt.expiration=${JWT_EXPIRATION:3600000}
app.auth.return-reset-code=${APP_AUTH_RETURN_RESET_CODE:false}
